#!/usr/bin/env python

import sys
import os


filter_path =  os.path.join(os.path.dirname(os.path.abspath(__file__)),"filters")
sys.path.insert(0, filter_path)

if __name__ == "__main__":
    module_name, pattern = sys.argv[1:]
    # print(condition, args)
    cond_mod = __import__(module_name)
    cond_clz = getattr(cond_mod, module_name.title())
    cond = cond_clz(pattern)
    if "setup" in dir(cond):
        cond.setup()
    for line in sys.stdin:
        res = cond.check(line)
        if res:
            print(res)
    if "release" in dir(cond):
        cond.release()
