#!/usr/bin/env python

import sys
sys.path.insert(0, "~/bin")

if __name__ == "__main__":
    module_name, pattern = sys.argv[1:]
    # print(condition, args)
    cond_mod = __import__(module_name)
    cond_clz = getattr(cond_mod, module_name.title())
    cond = cond_clz(pattern)
    if "setup" in dir(cond):
        cond.setup()
    for line in sys.stdin:
        if cond.check(line):
            print(line.strip())
    if "release" in dir(cond):
        cond.release()
